### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_c')

### ISSUE THREAD

**Issue by aaronmorillo7** [staskjs/vue-slick#108] opened 2021-10-02 19:05 UTC
Hello! I'm using Vue 3 with vue-slick, but when I try to use my component this issues appears, do you know what is the solution? Thanks in advance!

**Comment by thdq** [comment] 2021-11-07 00:55
Possible duplicate of https://github.com/staskjs/vue-slick/issues/106. Current vue-slick do not have Vue 3 support.

**Closed** 2023-06-05 11:38 UTC
